### ISSUE TITLE
HA_Strava isn't loading in Home Assistant Core 2022.5.0b0

### ISSUE THREAD

**Issue by stinkyfromusc** [madmic1314/ha_strava#10]
Updated this afternoon.  It was working this morning, and no longer after going to the Beta May release.

**Comment by stinkyfromusc** [comment]
I'm now seeing an error in my log: 

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 11:32:55 PM (1 occurrences)
Last logged: 11:32:55 PM

Setup failed for custom integration ha_strava: Unable to import component: cannot import name 'EVENT_TIME_CHANGED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

I'm going to close this and investigate further.

**Comment by stinkyfromusc** [comment]
This is still broken for me in Home Assistant 2022.5.0b6.

**Comment by madmic1314** [comment]
I don't run the HA beta at home - once I upgrade to 2022.5 I'll try and take a look at getting it working again.

https://developers.home-assistant.io/blog/2022/04/20/saying-goodbye-to-event_time_changed/ seems to be the reason.

It's used by the camera event to keep the images up to date, was checking every second if the image was updated. Will change to the new method and set the update interval to 60s.

**Comment by brewston** [comment]
Big thanks to @madmic1314 for maintaining this integration thus far. I couldn't get it working either :-( but if anyone's interested I created a _much simpler_  Appdaemon script to gather some of the basic stats (all time ride, YTD ride) I was interested in and create HA entities with them - It's here https://github.com/brewston/Home-Assistant---Strava

**Comment by bjornsivertsen** [comment]
Yes, thank you for your effort @madmic1314 !

**Comment by craibo** [comment]
I have a working version of this for anyone who is interested. Can be installed via HACS
https://github.com/craibo/ha_strava

**Comment by bjornsivertsen** [comment]
Thank you @craibo I will test it out later today! :)
