### ISSUE TITLE
integration not loaded (Can't remove it)

### ISSUE THREAD

**Issue by maobuz** [madmic1314/ha_strava#11]
After update

![image](https://user-images.githubusercontent.com/73724063/166955455-daafbf6d-0960-4475-ade3-04d76b4f434d.png)

Strava integration is totally broken , is impossible delete the integration, when i click on Delete nothing is happening and the integration not deleted.

![image](https://user-images.githubusercontent.com/73724063/166955296-67512204-5e9c-4460-a2a9-48380ab273b4.png)

what can i do now?

**Comment by madmic1314** [comment]
I would suggest you restart your HA instance, including the OS. Then delete the entities, integration and remove it from HACS. If that doesn't work, then more drastically you'll need to delete the custom component in the config folder. You'll get errors, but it'll be gone. You can try a re-install, and then a delete to try and clear it up.
