### ISSUE TITLE
HACS downloads to root

### ISSUE THREAD

**Issue by madmic1314** [madmic1314/ha_strava#2]
When added to HACS the repo files are downloaded to the root:
" repository.note_downloaded '/config/custom_components/' "

No idea why...

**Comment by madmic1314** [comment]
Have checked - all the other forks do this as well. All files are identical. No idea why this is. But stops the integration working with HACS

**Comment by stefanroelofs** [comment]
Can you check if it works if you change the version number to 0.2.1 (so MAJOR.MINOR.PATCH)

It says here that the version needs to be a valid version number like SemVer:
https://developers.home-assistant.io/docs/creating_integration_manifest/
https://semver.org

(I cann't test it myself right now, sorry)

**Comment by madmic1314** [comment]
Have done that - same issue.

What is weird, the original repo by codingcyclist has 12 forks (including yours) if you add those to HACS they all have this same issue. But if you add codingcyclist's repo it works. I can't find any differences at all. I'm really stumped.

Even if you fork the original repo, change nothing and add, same error!

**Comment by stefanroelofs** [comment]
I think it works ok for me now. I hand-deleted all strava files from the custom_components folder, then rebooted HA, and finally 'updated' strava again. For me it installed in the ha_strava folder.
I updated to version: a8949fa.

**Comment by madmic1314** [comment]
Resolved - this was caused by my HA instance having remnants of the previous HA_Strava integration.

You MUST fully remove this before adding this fork, else you'll have issues and need to fix this before it'll work.
