### ISSUE TITLE
Pace Div/0 Error when Distance is 0

### ISSUE THREAD

**Issue by markus99** [madmic1314/ha_strava#3]
Have my Peloton connected to Strava.  If I do a 'stretch' after a ride, this syncs to Strava, though with 0 distance.  This appears to be throwing Div/0 errors when trying to calculate the PACE for this event:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/ha_strava/sensor.py:334
Integration: HA Strava (documentation)
First occurred: 8:44:15 AM (2 occurrences)
Last logged: 8:44:24 AM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 404, in strava_data_update_event_handler
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/ha_strava/sensor.py", line 334, in state
    pace = self._data[CONF_SENSOR_MOVING_TIME] / (
ZeroDivisionError: float division by zero
```

![image](https://user-images.githubusercontent.com/2835274/150155038-67d126d2-d549-4611-b571-7ef0f2d324e4.png)

![image](https://user-images.githubusercontent.com/2835274/150155193-5b8aa960-2cd3-4c9a-a317-ba725c5a9e44.png)

**Comment by madmic1314** [comment]
Have put some code to capture this and set pace to 0 (a simple fix to this issue).
https://github.com/madmic1314/ha_strava/pull/4

Can you upgrade to this version and try again.

**Comment by maobuz** [comment]
@madmic1314  You are the best ! :****

removed HA integration + all sensors, then HACS integration, HACS repo. Reboot and then add: https://github.com/madmic1314/ha_strava 

Now Work Fine !

![image](https://user-images.githubusercontent.com/73724063/160012622-ac4bfdfa-119d-4e10-9dd7-6fe7ee54607f.png)

**Comment by madmic1314** [comment]
Ok, excellent. Can you test a 0 distance exercise and re-open if still an issue please?

**Comment by maobuz** [comment]
> 

Oook stay tuned ! this afternoon.

**Comment by woolf0007** [comment]
HI guys,
How you can set up speed, kcal, power ? I have only duration, pace, distance,trophies, kudos...

**Comment by madmic1314** [comment]
@woolf0007 - have you got something supplying this data in Strava? I don't so can't test I'm afraid. The sensors are all there in the code so should be setup if the data is coming from Strava (I'm still figuring this all out)

If you have got something supplying power data then please raise a new issue for this and we can begin to take a look.

**Comment by madmic1314** [comment]
@woolf0007 - have a look here: https://github.com/madmic1314/ha_strava/edit/master/README.md#configure-sensor-entities-for-different-types-of-strava-activities

Once you setup the integration in HA, then click configure and then submit. The next screen allows you to change the sensor types for each of the sensors.
![image](https://user-images.githubusercontent.com/53381142/160201416-72c2cbd7-dbca-4ec6-a411-e2cfce86fb22.png)

As before you need a power meter assigned to Strava for this to work. If you have any more issues, please open a new request.

**Comment by maobuz** [comment]
my settings 
![image](https://user-images.githubusercontent.com/73724063/160200644-7a01326f-ce37-46a6-978a-5940c92f06e4.png)

this is ok 

![image](https://user-images.githubusercontent.com/73724063/160200839-3339cffb-0b35-400a-9165-d2c9b33644f5.png)
![image](https://user-images.githubusercontent.com/73724063/160200893-d4cb92cd-48e0-4b35-a374-2dc20785fce7.png)

other acctivity no

![image](https://user-images.githubusercontent.com/73724063/160200963-f3e4fe4c-f7ad-4c8f-8375-cfd2ad1bf9ac.png)
![image](https://user-images.githubusercontent.com/73724063/160200987-220d41eb-09ef-4862-8564-8d8187817ec1.png)
![image](https://user-images.githubusercontent.com/73724063/160201016-151527a0-38f8-4509-909c-cfe9f9c61c48.png)
![image](https://user-images.githubusercontent.com/73724063/160201034-ca01a773-31c2-4535-b5a6-640bbc600661.png)

Today i have another activity but do not appear

![image](https://user-images.githubusercontent.com/73724063/160201859-fa22fe9c-9aa0-4fe6-b091-76537c4a7c45.png)


the count has stopped yesterday!
![image](https://user-images.githubusercontent.com/73724063/160201321-eacf1e3e-9090-4d3c-a909-142969dd1529.png)

and the test a 0 distance exercise not appear 
![image](https://user-images.githubusercontent.com/73724063/160201793-bb5bd710-7400-4399-87d9-39ef3ffdbdc6.png)

**Comment by woolf0007** [comment]
Yes, i did this config set before, but nothig happend, and yes, there are datas in speed, kcal etc... Maybe the activity types (snowboarding, canoing...) are the problems. Thx
